# -*- coding: utf-8 -*-
"""projeto - caio/ettore.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bZK09cHvzX4a-bmUVpWz_Y9Uts4dT_jD
"""

import getpass

def realizar_cadastro():
    qte_usuarios = int(input('Quantos usuários deseja cadastrar? '))
    usuario = []
    senha = []
    i = 1
    while i <= qte_usuarios:
        print(f'Usuario {i}')
        usuario.append(input('Nome de usuário: '))
        print('\n')
        senha.append(getpass.getpass('Senha: '))
        print('Usuário cadastrado')
        print('\n')
        i += 1
    i = 0

    with open('usuarios.csv', 'a') as arquivo_usuario:
        while i < len(usuario):
            usuarios = usuario[i]
            senhas = senha[i]
            arquivo_usuario.write(usuarios + ',' + senhas)
            arquivo_usuario.write('\n')
            i += 1

    arquivo_usuario.close()
    print('Gravado com sucesso!')


def realizar_login(usuario, senha):
    login = str(input('Digite o nome de usuário: '))
    senha_login = getpass.getpass('Digite a senha: ')
    i = 0

    while i < len(usuario):
        if usuario[i] == login and senha[i] == senha_login:
            print('\n')
            print("Login realizado com sucesso!")
            print('\n')
            return True
        i += 1

    print('\n')
    print("Acesso negado.")
    print('\n')
    print("Nome de usuário ou senha incorretos. Tente novamente.")
    return False


def cadastrar_cnh():
    cnh = input('Digite o número da sua CNH: ')
    with open('cnh.txt', 'w') as arquivo_cnh:
        arquivo_cnh.write(cnh)
    print("CNH cadastrada com sucesso.")
    print("\n")


def cadastrar_veiculo():
    cnh_valida = None
    cnh = input("Digite o número da CNH: ")
    with open('cnh.txt', 'r') as arquivo_cnh:
        for l in arquivo_cnh:
            if l.strip() == cnh:
                cnh_valida = cnh

    if cnh_valida:
        qte_carros = int(input('Quantos veículos deseja cadastrar? '))
        carros = []
        cores = []
        placas = []
        i = 1
        print("\n")

        while i <= qte_carros:
            print(f'Veículo {i}')
            carros.append(input('Carro: '))
            print('\n')
            cores.append(input('Cor do carro: '))
            print('\n')
            placas.append(input('Placa do carro: '))
            print('Veículo cadastrado')
            print('\n')
            i += 1

        with open('carros.txt', 'w') as arquivo_carros:
            i = 0
            while i < len(carros):
                carro = carros[i]
                cor = cores[i]
                placa = placas[i]
                arquivo_carros.write(carro + ';' + cor + ';' + placa)
                arquivo_carros.write('\n')
                i += 1
    else:
        print("CNH inválida. Não é possível cadastrar seu veículo.")


def menu():
    while True:
        print("Escolha uma opção:\nOPÇÃO 1: REALIZAR CADASTRO\nOPÇÃO 2: REALIZAR LOGIN\nOPÇÃO 3: SAIR")
        print(30 * '-')
        opcoes = str(input("O que voce deseja fazer? "))

        if opcoes == "1":
            realizar_cadastro()

        elif opcoes == "2":
            usuario = []
            senha = []
            # Lendo os usuários cadastrados
            with open('usuarios.csv', 'r') as arquivo_usuario:
                for linha in arquivo_usuario:
                    usuario_senha = linha.strip().split(',')
                    usuario.append(usuario_senha[0])
                    senha.append(usuario_senha[1])
            arquivo_usuario.close()

            login_sucesso = realizar_login(usuario, senha)

            if login_sucesso:
                while True:
                    print(30 * '-')
                    print("Escolha uma opção:\nOPÇÃO 1: CADASTRAR CNH\nOPÇÃO 2: REALIZAR CADASTRO DE VEÍCULO\nOPÇÃO 3: SAIR")
                    print(30 * '-')
                    opcoes = str(input("O que voce deseja fazer? "))

                    if opcoes == "1":
                        cadastrar_cnh()

                    elif opcoes == "2":
                        cadastrar_veiculo()

                    elif opcoes == '3':
                        print("Você saiu.")
                        return

        elif opcoes == "3":
            print("Você saiu.")
            return


menu()

